// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	feedback "ms-feedbacks/feedback"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

type UseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UseCase) EXPECT() *UseCase_Expecter {
	return &UseCase_Expecter{mock: &_m.Mock}
}

// CreateFeedback provides a mock function with given fields: _a0
func (_m *UseCase) CreateFeedback(_a0 feedback.Feedback) (feedback.Feedback, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateFeedback")
	}

	var r0 feedback.Feedback
	var r1 error
	if rf, ok := ret.Get(0).(func(feedback.Feedback) (feedback.Feedback, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(feedback.Feedback) feedback.Feedback); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(feedback.Feedback)
	}

	if rf, ok := ret.Get(1).(func(feedback.Feedback) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseCase_CreateFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFeedback'
type UseCase_CreateFeedback_Call struct {
	*mock.Call
}

// CreateFeedback is a helper method to define mock.On call
//   - _a0 feedback.Feedback
func (_e *UseCase_Expecter) CreateFeedback(_a0 interface{}) *UseCase_CreateFeedback_Call {
	return &UseCase_CreateFeedback_Call{Call: _e.mock.On("CreateFeedback", _a0)}
}

func (_c *UseCase_CreateFeedback_Call) Run(run func(_a0 feedback.Feedback)) *UseCase_CreateFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(feedback.Feedback))
	})
	return _c
}

func (_c *UseCase_CreateFeedback_Call) Return(_a0 feedback.Feedback, _a1 error) *UseCase_CreateFeedback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UseCase_CreateFeedback_Call) RunAndReturn(run func(feedback.Feedback) (feedback.Feedback, error)) *UseCase_CreateFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeedbacksByFigureID provides a mock function with given fields: idFigure, page
func (_m *UseCase) GetFeedbacksByFigureID(idFigure int, page int) (feedback.PaginatedFeedbacks, error) {
	ret := _m.Called(idFigure, page)

	if len(ret) == 0 {
		panic("no return value specified for GetFeedbacksByFigureID")
	}

	var r0 feedback.PaginatedFeedbacks
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (feedback.PaginatedFeedbacks, error)); ok {
		return rf(idFigure, page)
	}
	if rf, ok := ret.Get(0).(func(int, int) feedback.PaginatedFeedbacks); ok {
		r0 = rf(idFigure, page)
	} else {
		r0 = ret.Get(0).(feedback.PaginatedFeedbacks)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(idFigure, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseCase_GetFeedbacksByFigureID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeedbacksByFigureID'
type UseCase_GetFeedbacksByFigureID_Call struct {
	*mock.Call
}

// GetFeedbacksByFigureID is a helper method to define mock.On call
//   - idFigure int
//   - page int
func (_e *UseCase_Expecter) GetFeedbacksByFigureID(idFigure interface{}, page interface{}) *UseCase_GetFeedbacksByFigureID_Call {
	return &UseCase_GetFeedbacksByFigureID_Call{Call: _e.mock.On("GetFeedbacksByFigureID", idFigure, page)}
}

func (_c *UseCase_GetFeedbacksByFigureID_Call) Run(run func(idFigure int, page int)) *UseCase_GetFeedbacksByFigureID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *UseCase_GetFeedbacksByFigureID_Call) Return(_a0 feedback.PaginatedFeedbacks, _a1 error) *UseCase_GetFeedbacksByFigureID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UseCase_GetFeedbacksByFigureID_Call) RunAndReturn(run func(int, int) (feedback.PaginatedFeedbacks, error)) *UseCase_GetFeedbacksByFigureID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeedbackSummary provides a mock function with given fields: idFigure
func (_m *UseCase) GetFeedbackSummary(idFigure int) (feedback.Summary, error) {
	ret := _m.Called(idFigure)

	if len(ret) == 0 {
		panic("no return value specified for GetFeedbackSummary")
	}

	var r0 feedback.Summary
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (feedback.Summary, error)); ok {
		return rf(idFigure)
	}
	if rf, ok := ret.Get(0).(func(int) feedback.Summary); ok {
		r0 = rf(idFigure)
	} else {
		r0 = ret.Get(0).(feedback.Summary)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idFigure)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseCase_GetFeedbackSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeedbackSummary'
type UseCase_GetFeedbackSummary_Call struct {
	*mock.Call
}

// GetFeedbackSummary is a helper method to define mock.On call
//   - idFigure int
func (_e *UseCase_Expecter) GetFeedbackSummary(idFigure interface{}) *UseCase_GetFeedbackSummary_Call {
	return &UseCase_GetFeedbackSummary_Call{Call: _e.mock.On("GetFeedbackSummary", idFigure)}
}

func (_c *UseCase_GetFeedbackSummary_Call) Run(run func(idFigure int)) *UseCase_GetFeedbackSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *UseCase_GetFeedbackSummary_Call) Return(_a0 feedback.Summary, _a1 error) *UseCase_GetFeedbackSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UseCase_GetFeedbackSummary_Call) RunAndReturn(run func(int) (feedback.Summary, error)) *UseCase_GetFeedbackSummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
