// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorite.sql

package db

import (
	"context"
)

const createFavorite = `-- name: CreateFavorite :one
INSERT INTO favorite (
    id_user,
    id_figure
)
VALUES ($1, $2)
RETURNING id_user, id_figure, created_at
`

type CreateFavoriteParams struct {
	IDUser   int32 `json:"id_user"`
	IDFigure int32 `json:"id_figure"`
}

func (q *Queries) CreateFavorite(ctx context.Context, arg CreateFavoriteParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, createFavorite, arg.IDUser, arg.IDFigure)
	var i Favorite
	err := row.Scan(&i.IDUser, &i.IDFigure, &i.CreatedAt)
	return i, err
}

const deleteFavorite = `-- name: DeleteFavorite :exec
DELETE FROM favorite
WHERE id_user = $1
  AND id_figure = $2
`

type DeleteFavoriteParams struct {
	IDUser   int32 `json:"id_user"`
	IDFigure int32 `json:"id_figure"`
}

func (q *Queries) DeleteFavorite(ctx context.Context, arg DeleteFavoriteParams) error {
	_, err := q.db.Exec(ctx, deleteFavorite, arg.IDUser, arg.IDFigure)
	return err
}

const listFavoritesByUser = `-- name: ListFavoritesByUser :many
SELECT id_user, id_figure, created_at
FROM favorite
WHERE id_user = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFavoritesByUser(ctx context.Context, idUser int32) ([]Favorite, error) {
	rows, err := q.db.Query(ctx, listFavoritesByUser, idUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Favorite{}
	for rows.Next() {
		var i Favorite
		if err := rows.Scan(&i.IDUser, &i.IDFigure, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
