// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFeedbacksByFigureID = `-- name: CountFeedbacksByFigureID :one
SELECT COUNT(*)::bigint AS total_count
FROM feedback
WHERE id_figure = $1
`

func (q *Queries) CountFeedbacksByFigureID(ctx context.Context, idFigure pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countFeedbacksByFigureID, idFigure)
	var total_count int64
	err := row.Scan(&total_count)
	return total_count, err
}

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedback (description, rating, id_figure, id_user)
VALUES ($1, $2, $3, $4)
RETURNING id, description, rating,created_at, updated_at, id_figure, id_user
`

type CreateFeedbackParams struct {
	Description pgtype.Text `json:"description"`
	Rating      int32       `json:"rating"`
	IDFigure    pgtype.Int4 `json:"id_figure"`
	IDUser      pgtype.Int4 `json:"id_user"`
}

type CreateFeedbackRow struct {
	ID          int32            `json:"id"`
	Description pgtype.Text      `json:"description"`
	Rating      int32            `json:"rating"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	IDFigure    pgtype.Int4      `json:"id_figure"`
	IDUser      pgtype.Int4      `json:"id_user"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (CreateFeedbackRow, error) {
	row := q.db.QueryRow(ctx, createFeedback,
		arg.Description,
		arg.Rating,
		arg.IDFigure,
		arg.IDUser,
	)
	var i CreateFeedbackRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IDFigure,
		&i.IDUser,
	)
	return i, err
}

const getFeedbackSummary = `-- name: GetFeedbackSummary :one
SELECT
    COUNT(*)::bigint AS total_feedbacks,
    COALESCE(AVG(rating), 0)::float8 AS average_rating
FROM feedback
`

type GetFeedbackSummaryRow struct {
	TotalFeedbacks int64   `json:"total_feedbacks"`
	AverageRating  float64 `json:"average_rating"`
}

func (q *Queries) GetFeedbackSummary(ctx context.Context) (GetFeedbackSummaryRow, error) {
	row := q.db.QueryRow(ctx, getFeedbackSummary)
	var i GetFeedbackSummaryRow
	err := row.Scan(&i.TotalFeedbacks, &i.AverageRating)
	return i, err
}

const getFeedbacksByFigureID = `-- name: GetFeedbacksByFigureID :many
SELECT
    id,
    rating,
    description,
    created_at,
    updated_at,
    id_figure,
    id_user
FROM feedback
WHERE id_figure = $1
ORDER BY id ASC
LIMIT $2
OFFSET $3
`

type GetFeedbacksByFigureIDParams struct {
	IDFigure pgtype.Int4 `json:"id_figure"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) GetFeedbacksByFigureID(ctx context.Context, arg GetFeedbacksByFigureIDParams) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, getFeedbacksByFigureID, arg.IDFigure, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IDFigure,
			&i.IDUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
