// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Feedback struct {
	ID          int32            `json:"id"`
	Rating      int32            `json:"rating"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	IDFigure    pgtype.Int4      `json:"id_figure"`
	IDUser      pgtype.Int4      `json:"id_user"`
}
