// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (CreateFeedbackRow, error)
	GetFeedbacksByFigureID(ctx context.Context, idFigure pgtype.Int4) ([]GetFeedbacksByFigureIDRow, error)
}

var _ Querier = (*Queries)(nil)
